language: shell

os: osx
osx_image:
  - xcode11.3
  - xcode10.3
  - xcode9.3

install:
  - brew update
  - brew install cmake go rust || true

script:
- ./build.sh

before_cache:
- brew cleanup

cache:
  directories:
  - "/usr/local/Homebrew"
  - "$HOME/Library/Caches/Homebrew"
