language: shell

os: osx
osx_image:
  - xcode11.3
  - xcode10.3
  - xcode9.3

install:
  - brew update
  - brew install rust || true
  - brew upgrade cmake go

script:
- ./build.sh

before_cache:
- brew cleanup
- rm -rf nginx-1.16.1

cache:
  directories:
  - "$HOME/.cargo"
  - "/usr/local/Homebrew"
  - "$HOME/Library/Caches/Homebrew"
  - "$HOME/Library/Caches/go-build"
  - "$TRAVIS_BUILD_DIR/quiche"
